/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类: 
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Achievement Gotten!": "成就达成！",
    "(resets all progress)": "（重置所有进度）",
    "all diamonds": "所有钻石",
    "Audio": "音频",
    "Buy": "买",
    "Cancel": "取消",
    "Choose an option": "选择一个选项",
    "Claim": "宣称",
    "Collect": "收集",
    "Completing them provides you with a permanent Wicked Multiplier": "完成它们将为您提供永久的邪恶乘数",
    "Copy": "复制",
    "Copy save": "复制保存",
    "Courtyard": "庭院",
    "Delete save": "删除保存",
    "Dwarf Instructor and Dwarf Scholar become x10 more effective": "矮人讲师和矮人学者的效率提高 10 倍",
    "Dwarf University": "矮人大学",
    "Dwarves": "矮人",
    "Falkor at": "福尔科在",
    "Fresh horses!": "新鲜的马！",
    "Guide": "指引",
    "Hall of Giants": "巨人大厅",
    "Hammer": "锤子",
    "Hire": "聘请",
    "Humans": "人类",
    "Import save": "导入保存",
    "Incremental Fortress": "增量堡垒",
    "Join our Discord": "加入我们的 Discord",
    "Level 50": "50级",
    "Louigi Verona's Workshop": "Louigi Verona 的工作室",
    "Make": "制作",
    "Next mana in:": "下一个法力值: ",
    "Ogres": "食人魔",
    "Pick a topic...": "选择一个主题...",
    "Recast Giants": "重铸巨人",
    "Reincarnate": "轮回",
    "Reincarnate without upgrades": "重生不升级",
    "Reincarnation Mana:": "转生法力: ",
    "Save Game": "保存游戏",
    "Scientific notation": "科学计数法",
    "Seed": "种子",
    "to unlock": "解锁",
    "Toggle": "切换",
    "Tower of Dragons": "巨龙之塔",
    "Tower of Machines": "机器之塔",
    "Tower of Mages": "法师之塔",
    "Tower of Metals": "金属塔",
    "Tower of Mortals": "凡人之塔",
    "Turn it off": "把它关掉",
    "Unlock Wicked Quests": "解锁邪恶任务",
    "Unlock Wine Cellar": "解锁酒窖",
    "Volume": "体积",
    "Warlocks": "术士",
    "Weaklings": "弱者",
    "Witches": "女巫",
    "Wizards": "巫师",
    "Wyverns": "飞龙",
    "Boosts drinking time": "增加饮用时间",
    "Boosts drunken multiplier": "提高醉酒乘数",
    "Boosts hammer": "提升锤子",
    "Boosts ore": "提升矿石",
    "Boosts wine age": "提高酒龄",
    "Cup Size": "杯子尺寸",
    "current mana multiplier:": "当前法力乘数: ",
    "Grapes": "葡萄",
    "mana multiplier after reset:": "重置后的魔法倍数: ",
    "Messengers are on their way:": "信使正在路上: ",
    "wine": "葡萄酒",
    "Wine Age": "酒龄",
    "are on their way:": "在他们的路上: ",
    "Enemies": "敌人",
    "Tax collectors had done a good job": "收税员做得很好",
    "Taxes collected!": "税收已收！",
    "Close": "关闭",
    "Scroll down and get your people a drink!": "向下滚动，让你的人喝一杯！",
    "Wine cellar unlocked!": "酒窖已解锁！",
    "A humble squad of duplicitous dwarves is attacking one of our towers!": "一群卑鄙的两面派矮人正在攻击我们的一座塔楼！",
    "Hiring reward": "聘用奖励",
    "We are under attack!": "我们受到攻击了！",
    "times more powerful!": "威力倍增！",
    "Your other uncle has died": "你的另一个叔叔死了",
    "Dwarf Scholar": "矮人学者",
    "Hammer is": "锤子",
    "Inheritance is significant": "继承意义重大",
    "The gifts brought by the Royal Messengers are not random and are set at a x100 or x1,000 the current rate. Health points of the enemies are not random either and are set at x100 the current rate.": "皇家使者带来的礼物不是随机的，而是按当前比率设置为 x100 或 x1,000。 敌人的生命值也不是随机的，并且设置为当前速率的 100 倍。",
    "Keep in mind that when the Royal Messengers arrive, applying the Drunken Multiplier at that moment will increase those gifts accordingly. This also applies to things like Hiring Rewards and other upgrades that are dependent on current rate.": "请记住，当皇家使者到达时，在那一刻应用醉酒乘数会相应地增加这些礼物。 这也适用于雇佣奖励和其他取决于当前费率的升级。",
    "It is comprised from the creatures in the Tower of Mortals and the Tower of Mages: every 100 creatures add 1 giant. You need to click the \"Recast Giants\" button if you would like to recalculate the Giant Multiplier when more creatures are hired.": "它由凡人之塔和法师之塔的生物组成：每100个生物加1个巨人。 如果您想在雇用更多生物时重新计算巨人乘数，则需要单击“重铸巨人”按钮。",
    "There's also quite a bit of scrolling involved. While the need for it has been reduced slightly in this version, the issue remains. I already have ideas on how to address it, but suffice to say, I am aware of it.": "还涉及相当多的滚动。 虽然在此版本中对它的需求略有减少，但问题仍然存在。 我已经有了关于如何解决它的想法，但我只想说，我知道它。",
    "Fire Multiplier boosts Dwarves. It's not a permanent multiplier and is reset every reincarnation. It might make sense to check out the Wine Cellar when the Fire Multiplier is high, since at some point the dwarves might be the strongest race.": "火力乘数 可增强矮人。 它不是永久性的乘数，每次转世都会重置。 当火力乘数很高时检查酒窖是有意义的，因为在某些时候矮人可能是最强大的种族。",
    "Currently you cannot see which Alchemist Upgrade you can afford unless you actually click on its label. Hovering over the labels does allow you to see the price, but it would be nice if the labels become active or inactive depending on whether you can afford them. Unfortunately, I haven't yet been able to implement a reliable solution.": "目前，除非您实际单击其标签，否则您无法看到您可以负担得起哪种炼金术士升级。 将鼠标悬停在标签上确实可以让您看到价格，但如果标签根据您是否负担得起而变为活动或非活动状态，那就更好了。 不幸的是，我还没有能够实施可靠的解决方案。",
    "Each quest requires you to hire 66 of the relevant mortal which will trigger the corresponding counter in the Wicked Quests box. When the counter reaches 666, the Wicked Multiplier will be incremented by 1.": "每个任务都需要您雇用 66 个相关凡人，这将触发 邪恶的任务 框中的相应计数器。 当计数器达到 666 时，邪恶乘数将增加 1。",
    "Apart from being an awesome dragon that boosts his sister Eborsisk, Smaug also boosts the Graveyard. Every 50 levels of Smaug increment a special multiplier. Because of that if Smaug's level is under 50, the Graveyard won't function.": "Smaug 除了是一条可以提升他的姐妹 Eborsisk 的超棒龙之外，还可以提升墓地。 每 50 级 Smaug 都会增加一个特殊的乘数。 因此，如果 Smaug 的等级低于 50，墓地将无法使用。",
    "In order to increment the multiplier, you must reach the target in each of the Doomed Artifacts. Use the \">>>\" button to switch between artifacts and fill each one up. When done, click the \"Next target\" button which will increment the Graveyard Multiplier and set the next target.": "为了增加乘数，您必须达到每个 注定的神器 中的目标。 使用“>>>”按钮在工件之间切换并填充每个工件。完成后，单击“下一个目标”按钮，这将增加 墓地乘数 并设置下一个目标。",
    "Diamonds increase the power of giants. Keep in mind that the price is the same for all diamonds and will grow with every purchase. Therefore, think carefully which giants to upgrade first!": "钻石增加巨人的力量。 请记住，所有钻石的价格都是一样的，并且会随着每次购买而上涨。 因此，请仔细考虑先升级哪些巨头！",
    "Alchemist provides upgrades that are unlocked based on a variety of conditions, mostly around the amount of creatures or machines in the towers. In order to buy the upgrade, you must first select its label. Hovering over the labels allows you to see the description of each upgrade.": "炼金术士提供根据各种条件解锁的升级，主要围绕塔中生物或机器的数量。 要购买升级，您必须首先选择其标签。 将鼠标悬停在标签上可以查看每个升级的描述。",
    "If you hire more creatures midway, the counter will stop. Its progress will not be reset, but that would mean you've botched the challenge for this run and would need to wait for a reincarnation to finish it.": "如果您在中途雇用更多生物，计数器将停止。 它的进度不会被重置，但这意味着你已经搞砸了这次挑战的挑战，需要等待轮回来完成它。",
    "Medallions are achievements that are awarded when you reach certain hiring milestones, such as 10 Weaklings, 50 Weaklings, 100 Weaklings and so on for every creature and machine. Each milestone gives the player a hiring reward. This reward depends on the current rate, so ensuring that the Drunken Multiplier in the Wine Cellar is active when reaching the milestone will make the reward higher.": "奖章是当您达到某些招聘里程碑时授予的成就，例如每个生物和机器达到 10 个 弱者、50 个 弱者、100 个 弱者 等等。 每个里程碑都会给玩家一份雇佣奖励。 该奖励取决于当前比率，因此确保酒窖中的醉酒乘数在达到里程碑时处于活动状态将使奖励更高。",
    "of the game - a very early release. Therefore, keep in mind that there is little guarantee that your save is going to be compatible with future versions. Instead, consider this version as a standalone experience.": "游戏 - 非常早的版本。 因此，请记住，无法保证您的存档与未来版本兼容。 相反，请将此版本视为独立体验。",
    "Wine Cellar applies the Drunken Multiplier to one of either races in the Towers of Mortals and Mages. Depending on the situation, it might be beneficial to provide drinks to a specific race.": "酒窖将醉酒乘数应用于凡人之塔和法师之塔中的任一种族。 根据情况，为特定种族提供饮料可能是有益的。",
    "A small regiment of treacherous humans is attacking one of our towers!": "一小群奸诈的人类正在攻击我们的一座塔楼！",
    "Another important bit is balance and pacing. It's one of those things that require lots of testing and tweaking and will improve over time.": "另一个重要的一点是平衡和节奏。 这是需要大量测试和调整的事情之一，并且会随着时间的推移而改进。",
    "color": "颜色",
    "Completing all the quests provides you with a permanent Wicked Multiplier of x5, which is applied to the current rate after all of the other upgrades.": "完成所有任务后，您将获得 5 倍的永久邪恶乘数，在所有其他升级后应用于当前比率。",
    "Finally, Reincarnation upgrades right now are very basic. I will probably come up with a more interesting prestige system for the next version. Stay tuned!": "最后，现在的轮回升级非常基础。 我可能会为下一个版本想出一个更有趣的声望系统。 敬请关注！",
    "Giant Multiplier is a poweful upgrade that is applied to the current rate after all of the other upgrades.": "巨人乘数 是一个强大的升级，在所有其他升级之后应用于当前速率。",
    "Graveyard Multiplier is a poweful upgrade that is applied to the current rate after all of the other upgrades.": "墓地乘数 是一项强大的升级，在所有其他升级之后应用于当前速率。",
    "I am fairly satisfied with the current version, but I also view it as just the beginning.": "我对当前版本相当满意，但我也认为它只是一个开始。",
    "Incremental Fortress is the kind of game that benefits from having a variety of fun upgrades and supplemental mechanics to be interesting.": "增量堡垒 是一种受益于各种有趣的升级和补充机制而变得有趣的游戏。",
    "Incremental Fortress supports offline mining by default. Offline mining runs at 10% efficiency.": "增量堡垒默认支持离线挖矿。 离线挖矿以 10% 的效率运行。",
    "Mana multiplier is a powerful upgrade and is applied to the rate after all of the other upgrades.": "法力乘数是一个强大的升级，并在所有其他升级之后应用于速率。",
    "Note: Reincarnation button becomes visible when you mine 1 Mana. You need a minimum of x2 to reincarnate during your first run.": "注意：当您开采 1 点法力值时，转生按钮会变得可见。 在第一次运行期间，您至少需要 x2 才能转世。",
    "Note: you can tell when someone is drinking by the": "注意：您可以通过",
    "of the rate indicator": "率指标",
    "One of the most common questions about an incremental game - which stage is the end of content?": "关于增量游戏最常见的问题之一——哪个阶段是内容的结束？",
    "The current IF release ends when you unlock the Graveyard. Obviously, there's a lot for the player to do there, but there is currently nothing beyond that.": "当您解锁墓地时，当前的 IF 版本结束。 显然，玩家可以在那里做很多事情，但目前除此之外别无他法。",
    "There are also powerful Medallion Alchemist Upgrades that are unlocked at 10, 20 and 30 medallions.": "还有强大的奖章炼金术士升级，可在 10、20 和 30 个奖章时解锁。",
    "There are currently no prestige upgrades for the Graveyard, but it has a dependency on Smaug, so be sure to read the section on Smaug.": "目前墓地没有声望升级，但它依赖于史矛革，所以一定要阅读关于史矛革的部分。",
    "Therefore, it makes sense to maximize your rate when you see that the Messengers are about to arrive.": "因此，当您看到信使即将到达时，最大化您的速率是有意义的。",
    "This is": "这是",
    "When Smaug's level is 50, this special multiplier is x1. When it's a 100 the multiplier is x2, and so on.": "当 Smaug 的等级为 50 时，此特殊乘数为 x1。 当它是 100 时，乘数是 x2，依此类推。",
    "Be Very Afraid!": "非常害怕！",
    "Doubles the power of weaklings": "弱者的力量翻倍",
    "Doubles the power of ogres": "食人魔的力量翻倍",
    "Doubles the power of humans": "人类的力量翻倍",
    "Doubles the power of dwarves": "矮人的力量翻倍",
    "Dwarf Adventure": "矮人冒险",
    "Healthy Diet": "健康饮食",
    "Ordinary but Ambitious": "平凡但有野心",
    "Small Fists": "小拳头",
    "The Dwarf Age": "矮人时代",
    "Weak Force": "弱的力量",
    "Massive Gates": "巨型大门",
    "Fortress Multiplier +1%": "堡垒乘数 +1%",
    "The Brute Squad": "蛮力小队",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Garden": "花园",
    "Smaug": "Smaug",
    "Alchemist": "炼金术士",
    "Giant Multiplier": "巨人乘数",
    "Fire Multiplier": "火力乘数",
    "Offline mining": "离线挖矿",
    "Known issues": "已知的问题",
    "Wicked Quests": "邪恶的任务",
    "End of content": "内容结束",
    "Diamonds": "钻石",
    "Future plans": "未来的计划",
    "Compatibility": "兼容性",
    "Reincarnation": "投胎",
    "Wine Cellar": "酒窖",
    "Graveyard": "墓地",
    "Medallions": "奖章",
    "Messengers": "信使",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑: ",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式: ",
    "In-line Exponent: ": "直列指数: ",
    "Single-Tab Mode: ": "单标签模式: ",
    "Time Played: ": "已玩时长: ",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示: ",
    "Succubi: ": "魅魔: ",
    "Skeletons: ": "骷髅: ",
    "Spirits: ": "精灵: ",
    "Price: ": "价格: ",
    "Ore Mines: ": "矿山: ",
    "Drunken Multiplier: ": "醉酒乘数: ",
    "Size: ": "尺寸: ",
    "Cheiroballistras: ": "手榴弹: ",
    "Catapults: ": "弹射器: ",
    "Crossbows: ": "弩: ",
    "Weaklings: ": "弱者: ",
    "Ore: ": "矿石: ",
    "Dwarves: ": "矮人: ",
    "Humans: ": "人类: ",
    "Collect: ": "收集: ",
    "Power: ": "力量: ",
    "Loot: ": "战利品: ",
    "Enemy HP: ": "敌人生命值: ",
    "Ogres: ": "食人魔: ",
    "Specters: ": "幽灵: ",
    "Time: ": "时间: ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)k$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字: (\d+)
//逗号: ([\d\.,]+)
//小数点: ([\d\.]+)
//原样输出的字段: (.+)
//换行加空格: \n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.]+)\/s$/, '$1\/秒'],
	[/^\+([\d\.]+)\/s$/, '+$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^Raise ([\d\.,]+)$/, '增加 $1'],
    [/^Make ([\d\.,]+)$/, '制作 $1'],
    [/^Hire ([\d\.,]+)$/, '雇佣 $1'],
    [/^Buy ([\d\.,]+)$/, '购买 $1'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^([\d\.,]+) Humans$/, '$1 人类'],
    [/^([\d\.,]+) humans$/, '$1 人类'],
    [/^([\d\.,]+) Weaklings$/, '$1 弱者'],
    [/^([\d\.,]+) weaklings$/, '$1 弱者'],
    [/^([\d\.,]+) Crossbows$/, '$1 弩'],
    [/^([\d\.,]+) crossbows$/, '$1 弩'],
    [/^([\d\.,]+) Wizards$/, '$1 巫师'],
    [/^([\d\.,]+) wizards$/, '$1 巫师'],
    [/^([\d\.,]+) Ogres$/, '$1 食人魔'],
    [/^([\d\.,]+) ogres$/, '$1 食人魔'],
    [/^([\d\.,]+) Dwarves$/, '$1 矮人'],
    [/^([\d\.,]+) dwarves$/, '$1 矮人'],
    [/^([\d\.,]+) Medallions$/, '$1 奖章'],
    [/^([\d\.,]+) medallions$/, '$1 奖章'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本: $1 点数'],
    [/^Req: (.+) elves$/, '要求: $1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求: $1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途: $1\/'],
    [/^workers: (\d+)\/$/, '工人: $1\/'],

]);