/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类: 
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Achievement Gotten!": "成就达成！",
    "(resets all progress)": "（重置所有进度）",
    "all diamonds": "所有钻石",
    "Audio": "音频",
    "Buy": "买",
    "Cancel": "取消",
    "Choose an option": "选择一个选项",
    "Claim": "宣称",
    "Collect": "收集",
    "Completing them provides you with a permanent Wicked Multiplier": "完成它们将为您提供永久的邪恶乘数",
    "Copy": "复制",
    "Copy save": "复制保存",
    "Courtyard": "庭院",
    "Delete save": "删除保存",
    "Dwarf Instructor and Dwarf Scholar become x10 more effective": "矮人讲师和矮人学者的效率提高 10 倍",
    "Dwarf University": "矮人大学",
    "Dwarves": "矮人",
    "Falkor at": "福尔科在",
    "Fresh horses!": "新鲜的马！",
    "Guide": "指引",
    "Hall of Giants": "巨人大厅",
    "Hammer": "锤子",
    "Hire": "雇佣",
    "Humans": "人类",
    "Import save": "导入保存",
    "Incremental Fortress": "增量堡垒",
    "Join our Discord": "加入我们的 Discord",
    "Level 50": "50级",
    "Louigi Verona's Workshop": "Louigi Verona 的工作室",
    "Make": "制作",
    "Next mana in:": "下一个法力值: ",
    "Ogres": "食人魔",
    "Pick a topic...": "选择一个主题...",
    "Recast Giants": "重铸巨人",
    "Reincarnate": "轮回",
    "Reincarnate without upgrades": "重生不升级",
    "Reincarnation Mana:": "转生法力: ",
    "Save Game": "保存游戏",
    "Scientific notation": "科学计数法",
    "Seed": "种子",
    "to unlock": "解锁",
    "Toggle": "切换",
    "Tower of Dragons": "巨龙之塔",
    "Tower of Machines": "机器之塔",
    "Tower of Mages": "法师之塔",
    "Tower of Metals": "金属塔",
    "Tower of Mortals": "凡人之塔",
    "Turn it off": "把它关掉",
    "Unlock Wicked Quests": "解锁邪恶任务",
    "Unlock Wine Cellar": "解锁酒窖",
    "Volume": "体积",
    "Warlocks": "术士",
    "Weaklings": "弱者",
    "Witches": "女巫",
    "Wizards": "巫师",
    "Wyverns": "飞龙",
    "Boosts drinking time": "增加饮用时间",
    "Boosts drunken multiplier": "提高醉酒乘数",
    "Boosts hammer": "提升锤子",
    "Boosts ore": "提升矿石",
    "Boosts wine age": "提高酒龄",
    "Cup Size": "杯子尺寸",
    "current mana multiplier:": "当前法力乘数: ",
    "Grapes": "葡萄",
    "mana multiplier after reset:": "重置后的魔法倍数: ",
    "Messengers are on their way:": "信使正在路上: ",
    "wine": "葡萄酒",
    "Wine Age": "酒龄",
    "are on their way:": "在他们的路上: ",
    "Enemies": "敌人",
    "Tax collectors had done a good job": "收税员做得很好",
    "Taxes collected!": "税收已收！",
    "Close": "关闭",
    "Scroll down and get your people a drink!": "向下滚动，让你的人喝一杯！",
    "Wine cellar unlocked!": "酒窖已解锁！",
    "A humble squad of duplicitous dwarves is attacking one of our towers!": "一群卑鄙的两面派矮人正在攻击我们的一座塔楼！",
    "Hiring reward": "聘用奖励",
    "We are under attack!": "我们受到攻击了！",
    "times more powerful!": "威力倍增！",
    "Your other uncle has died": "你的另一个叔叔死了",
    "Dwarf Scholar": "矮人学者",
    "Hammer is": "锤子",
    "Inheritance is significant": "继承意义重大",
    "The gifts brought by the Royal Messengers are not random and are set at a x100 or x1,000 the current rate. Health points of the enemies are not random either and are set at x100 the current rate.": "皇家使者带来的礼物不是随机的，而是按当前比率设置为 x100 或 x1,000。 敌人的生命值也不是随机的，并且设置为当前速率的 100 倍。",
    "Keep in mind that when the Royal Messengers arrive, applying the Drunken Multiplier at that moment will increase those gifts accordingly. This also applies to things like Hiring Rewards and other upgrades that are dependent on current rate.": "请记住，当皇家使者到达时，在那一刻应用醉酒乘数会相应地增加这些礼物。 这也适用于雇佣奖励和其他取决于当前费率的升级。",
    "It is comprised from the creatures in the Tower of Mortals and the Tower of Mages: every 100 creatures add 1 giant. You need to click the \"Recast Giants\" button if you would like to recalculate the Giant Multiplier when more creatures are hired.": "它由凡人之塔和法师之塔的生物组成：每100个生物加1个巨人。 如果您想在雇用更多生物时重新计算巨人乘数，则需要单击“重铸巨人”按钮。",
    "There's also quite a bit of scrolling involved. While the need for it has been reduced slightly in this version, the issue remains. I already have ideas on how to address it, but suffice to say, I am aware of it.": "还涉及相当多的滚动。 虽然在此版本中对它的需求略有减少，但问题仍然存在。 我已经有了关于如何解决它的想法，但我只想说，我知道它。",
    "Fire Multiplier boosts Dwarves. It's not a permanent multiplier and is reset every reincarnation. It might make sense to check out the Wine Cellar when the Fire Multiplier is high, since at some point the dwarves might be the strongest race.": "火力乘数 可增强矮人。 它不是永久性的乘数，每次转世都会重置。 当火力乘数很高时检查酒窖是有意义的，因为在某些时候矮人可能是最强大的种族。",
    "Currently you cannot see which Alchemist Upgrade you can afford unless you actually click on its label. Hovering over the labels does allow you to see the price, but it would be nice if the labels become active or inactive depending on whether you can afford them. Unfortunately, I haven't yet been able to implement a reliable solution.": "目前，除非您实际单击其标签，否则您无法看到您可以负担得起哪种炼金术士升级。 将鼠标悬停在标签上确实可以让您看到价格，但如果标签根据您是否负担得起而变为活动或非活动状态，那就更好了。 不幸的是，我还没有能够实施可靠的解决方案。",
    "Each quest requires you to hire 66 of the relevant mortal which will trigger the corresponding counter in the Wicked Quests box. When the counter reaches 666, the Wicked Multiplier will be incremented by 1.": "每个任务都需要您雇用 66 个相关凡人，这将触发 邪恶的任务 框中的相应计数器。 当计数器达到 666 时，邪恶乘数将增加 1。",
    "Apart from being an awesome dragon that boosts his sister Eborsisk, Smaug also boosts the Graveyard. Every 50 levels of Smaug increment a special multiplier. Because of that if Smaug's level is under 50, the Graveyard won't function.": "Smaug 除了是一条可以提升他的姐妹 Eborsisk 的超棒龙之外，还可以提升墓地。 每 50 级 Smaug 都会增加一个特殊的乘数。 因此，如果 Smaug 的等级低于 50，墓地将无法使用。",
    "In order to increment the multiplier, you must reach the target in each of the Doomed Artifacts. Use the \">>>\" button to switch between artifacts and fill each one up. When done, click the \"Next target\" button which will increment the Graveyard Multiplier and set the next target.": "为了增加乘数，您必须达到每个 注定的神器 中的目标。 使用“>>>”按钮在工件之间切换并填充每个工件。完成后，单击“下一个目标”按钮，这将增加 墓地乘数 并设置下一个目标。",
    "Diamonds increase the power of giants. Keep in mind that the price is the same for all diamonds and will grow with every purchase. Therefore, think carefully which giants to upgrade first!": "钻石增加巨人的力量。 请记住，所有钻石的价格都是一样的，并且会随着每次购买而上涨。 因此，请仔细考虑先升级哪些巨头！",
    "Alchemist provides upgrades that are unlocked based on a variety of conditions, mostly around the amount of creatures or machines in the towers. In order to buy the upgrade, you must first select its label. Hovering over the labels allows you to see the description of each upgrade.": "炼金术士提供根据各种条件解锁的升级，主要围绕塔中生物或机器的数量。 要购买升级，您必须首先选择其标签。 将鼠标悬停在标签上可以查看每个升级的描述。",
    "If you hire more creatures midway, the counter will stop. Its progress will not be reset, but that would mean you've botched the challenge for this run and would need to wait for a reincarnation to finish it.": "如果您在中途雇用更多生物，计数器将停止。 它的进度不会被重置，但这意味着你已经搞砸了这次挑战的挑战，需要等待轮回来完成它。",
    "Medallions are achievements that are awarded when you reach certain hiring milestones, such as 10 Weaklings, 50 Weaklings, 100 Weaklings and so on for every creature and machine. Each milestone gives the player a hiring reward. This reward depends on the current rate, so ensuring that the Drunken Multiplier in the Wine Cellar is active when reaching the milestone will make the reward higher.": "奖章是当您达到某些雇佣里程碑时授予的成就，例如每个生物和机器达到 10 个 弱者、50 个 弱者、100 个 弱者 等等。 每个里程碑都会给玩家一份雇佣奖励。 该奖励取决于当前比率，因此确保酒窖中的醉酒乘数在达到里程碑时处于活动状态将使奖励更高。",
    "of the game - a very early release. Therefore, keep in mind that there is little guarantee that your save is going to be compatible with future versions. Instead, consider this version as a standalone experience.": "游戏 - 非常早的版本。 因此，请记住，无法保证您的存档与未来版本兼容。 相反，请将此版本视为独立体验。",
    "Wine Cellar applies the Drunken Multiplier to one of either races in the Towers of Mortals and Mages. Depending on the situation, it might be beneficial to provide drinks to a specific race.": "酒窖将醉酒乘数应用于凡人之塔和法师之塔中的任一种族。 根据情况，为特定种族提供饮料可能是有益的。",
    "A small regiment of treacherous humans is attacking one of our towers!": "一小群奸诈的人类正在攻击我们的一座塔楼！",
    "Another important bit is balance and pacing. It's one of those things that require lots of testing and tweaking and will improve over time.": "另一个重要的一点是平衡和节奏。 这是需要大量测试和调整的事情之一，并且会随着时间的推移而改进。",
    "color": "颜色",
    "Completing all the quests provides you with a permanent Wicked Multiplier of x5, which is applied to the current rate after all of the other upgrades.": "完成所有任务后，您将获得 5 倍的永久邪恶乘数，在所有其他升级后应用于当前比率。",
    "Finally, Reincarnation upgrades right now are very basic. I will probably come up with a more interesting prestige system for the next version. Stay tuned!": "最后，现在的轮回升级非常基础。 我可能会为下一个版本想出一个更有趣的声望系统。 敬请关注！",
    "Giant Multiplier is a poweful upgrade that is applied to the current rate after all of the other upgrades.": "巨人乘数 是一个强大的升级，在所有其他升级之后应用于当前速率。",
    "Graveyard Multiplier is a poweful upgrade that is applied to the current rate after all of the other upgrades.": "墓地乘数 是一项强大的升级，在所有其他升级之后应用于当前速率。",
    "I am fairly satisfied with the current version, but I also view it as just the beginning.": "我对当前版本相当满意，但我也认为它只是一个开始。",
    "Incremental Fortress is the kind of game that benefits from having a variety of fun upgrades and supplemental mechanics to be interesting.": "增量堡垒 是一种受益于各种有趣的升级和补充机制而变得有趣的游戏。",
    "Incremental Fortress supports offline mining by default. Offline mining runs at 10% efficiency.": "增量堡垒默认支持离线挖矿。 离线挖矿以 10% 的效率运行。",
    "Mana multiplier is a powerful upgrade and is applied to the rate after all of the other upgrades.": "法力乘数是一个强大的升级，并在所有其他升级之后应用于速率。",
    "Note: Reincarnation button becomes visible when you mine 1 Mana. You need a minimum of x2 to reincarnate during your first run.": "注意：当您开采 1 点法力值时，转生按钮会变得可见。 在第一次运行期间，您至少需要 x2 才能转世。",
    "Note: you can tell when someone is drinking by the": "注意：您可以通过",
    "of the rate indicator": "率指标",
    "One of the most common questions about an incremental game - which stage is the end of content?": "关于增量游戏最常见的问题之一——哪个阶段是内容的结束？",
    "The current IF release ends when you unlock the Graveyard. Obviously, there's a lot for the player to do there, but there is currently nothing beyond that.": "当您解锁墓地时，当前的 IF 版本结束。 显然，玩家可以在那里做很多事情，但目前除此之外别无他法。",
    "There are also powerful Medallion Alchemist Upgrades that are unlocked at 10, 20 and 30 medallions.": "还有强大的奖章炼金术士升级，可在 10、20 和 30 个奖章时解锁。",
    "There are currently no prestige upgrades for the Graveyard, but it has a dependency on Smaug, so be sure to read the section on Smaug.": "目前墓地没有声望升级，但它依赖于史矛革，所以一定要阅读关于史矛革的部分。",
    "Therefore, it makes sense to maximize your rate when you see that the Messengers are about to arrive.": "因此，当您看到信使即将到达时，最大化您的速率是有意义的。",
    "This is": "这是",
    "When Smaug's level is 50, this special multiplier is x1. When it's a 100 the multiplier is x2, and so on.": "当 Smaug 的等级为 50 时，此特殊乘数为 x1。 当它是 100 时，乘数是 x2，依此类推。",
    "Be Very Afraid!": "非常害怕！",
    "Doubles the power of weaklings": "弱者的力量翻倍",
    "Doubles the power of ogres": "食人魔的力量翻倍",
    "Doubles the power of humans": "人类的力量翻倍",
    "Doubles the power of dwarves": "矮人的力量翻倍",
    "Dwarf Adventure": "矮人冒险",
    "Healthy Diet": "健康饮食",
    "Ordinary but Ambitious": "平凡但有野心",
    "Small Fists": "小拳头",
    "The Dwarf Age": "矮人时代",
    "Weak Force": "弱的力量",
    "Massive Gates": "巨型大门",
    "Fortress Multiplier +1%": "堡垒乘数 +1%",
    "The Brute Squad": "蛮力小队",
    "Copied": "已复制",
    "Boosts Dagahra": "提升Dagahra",
    "Boosts Eborsisk": "提升Eborsisk",
    "Boosts Falkor": "提升Falkor",
    "Boosts Fire Multiplier": "提升火力倍增器",
    "Boosts skeletons": "提升骷髅",
    "Boosts Smaug": "提升Smaug",
    "Boosts specters": "提升幽灵",
    "Boosts spirits": "提升精灵",
    "Dagahra": "Dagahra",
    "Eborsisk": "埃博西斯克",
    "Falkor": "Falkor",
    "Fire Multiplier:": "火力倍增器：",
    "Giant Multiplier:": "巨大的乘数：",
    "Graveyard Multiplier:": "墓地乘数：",
    "Katla": "Katla",
    "Altar of Winds": "风之祭坛",
    "Aviary": "鸟舍",
    "Back to the Finite World": "回到有限世界",
    "Buy max": "购买最大",
    "Buy several": "买几个",
    "Cannibals": "食人者",
    "Catch": "抓捕",
    "Complete Transmigration": "完全穿越",
    "Deal": "交易",
    "Deleting your save resets all progress": "删除你的保存会重置所有进度",
    "Donate": "捐赠",
    "Double fortified humans": "双强化人类",
    "Double fortified warlocks": "双强化术士",
    "Double fortified wizards": "双强化法师",
    "Enter the Infinite Library": "进入无限图书馆",
    "Flask": "烧瓶",
    "For Chrome, see here:": "对于 Chrome，请参阅此处：",
    "For Firefox, see here:": "对于 Firefox，请参阅此处：",
    "Fortifications": "防御工事",
    "Fortress Level after reset:": "重置后的要塞等级：",
    "Fortress Level:": "要塞等级：",
    "Gandlor's Cave": "甘德洛洞穴",
    "Guards of the Outer Wall:": "外墙守卫：",
    "https://developer.chrome.com/docs/devtools/storage/localstorage/": "https://developer.chrome.com/docs/devtools/storage/localstorage/",
    "https://firefox-source-docs.mozilla.org/devtools-user/storage_inspector/local_storage_session_storage/index.html": "https://firefox-source-docs.mozilla.org/devtools-user/storage_inspector/local_storage_session_storage/index.html",
    "If you're seeing this, you must have tried to load either a broken or an incompatible save.": "如果您看到此情况，则您一定尝试加载损坏或不兼容的保存。",
    "In order to reset the game, please google on how to access Local Storage of your browser and delete the save called": "为了重置游戏，请谷歌如何访问浏览器的本地存储并删除名为的保存",
    "incremental_fortress0.5": "增量堡垒0.5",
    "Known Ingredients": "已知成分",
    "Known Recipes": "已知食谱",
    "Mana:": "法力：",
    "Messenger alerts": "信使提醒",
    "Mobile Experience": "移动体验",
    "Mystic Workshop": "神秘工坊",
    "Necromancer": "死灵法师",
    "Necropolis": "大墓地",
    "Outer Wall": "外墙",
    "Raiders": "攻略",
    "Reach 5000% to activate": "达到5000%即可激活",
    "Receive Your Library Card": "收到您的图书卡",
    "Scraps of Ancient Knowledge": "古代知识的碎片",
    "Transmigrate": "轮回",
    "Transmigration": "轮回",
    "Treasury": "财政部",
    "Yes please": "是的，请",
    ". A modified Archon based on his work was made by": "。 根据他的作品修改了执政官",
    ". These have also been converted to SVGs.": "。 这些也已转换为 SVG。",
    "Although IF was designed for desktop, the game performs quite decently on mobile. Chrome would be your best bet.": "虽然《IF》是为桌面设计的，但该游戏在移动设备上的表现相当不错。 Chrome 将是您最好的选择。",
    "and": "和",
    "Backgrounds have been made with Midjourney and edited in GIMP.": "背景是用 Midjourney 制作并在 GIMP 中编辑的。",
    "Duncan.": "邓肯.",
    "Gandlor's Cave monsters are by": "甘德洛洞穴的怪物是",
    "Haunted Multiplier:": "闹鬼乘数：",
    "I'd like to mention": "我想提一下",
    "Manveru": "曼韦鲁",
    "Not really a guide. More like": "不是真正的指南。 更像",
    "of the game. It is not compatible with previous versions and has only superficial relation to its previous incarnations.": "的游戏。 它与以前的版本不兼容，并且与其以前的版本只有表面关系。",
    "scraps of ancient knowledge": "古代知识的碎片",
    "Special thanks goes to my Discord crew. Their enthusiasm for the game was very inspiring and helped me get through months of development. And then everyone spent weeks play testing and providing detailed feedback and ideas.": "特别感谢我的 Discord 团队。 他们对游戏的热情非常鼓舞人心，帮助我度过了几个月的开发过程。 然后每个人都花了几周的时间进行测试并提供详细的反馈和想法。",
    "Stephen Challener (Redshrike)": "史蒂芬·查勒纳（红鹩莺）",
    "Support Louigi 💚︎": "支持 Louigi💚︎",
    "The recommended amount for first transmigration is 22. The minimum amount which would at all make sense is 4, allowing you to purchase \"The Infinite Rulebook\" and \"Empowerment\"": "第一次穿越的推荐数量是22。最低数量是4，可以购买“无限规则书”和“赋能”",
    "The thing you cannot currently do is click on the hammer quickly without activating zooming in, but I am planning to address it at some point.": "目前您无法做的就是快速单击锤子而不激活放大，但我计划在某个时候解决这个问题。",
    "Tip: if the element has a tooltip, like Alchemist upgrades, a long press on an element will show the tooltip without activating the element.": "提示：如果元素有工具提示，例如炼金术士升级，长按元素将显示工具提示，而不激活该元素。",
    "Transmigration takes you out of spacetime. The transmigration button becomes visible when you mine 1 Mana. You need a minimum of x2 to transmigrate during your first run.": "穿越带你脱离时空。 当您开采 1 点法力时，轮回按钮就会变得可见。 在第一次运行期间，您至少需要 x2 才能进行穿越。",
    "undefined": "不明确的",
    "Unit and item sprites are based on DENZI's excellent CC0 sprite collection. I have used Inkscape to convert them to SVGs.": "单位和物品精灵基于 DENZI 优秀的 CC0 精灵集合。 我使用 Inkscape 将它们转换为 SVG。",
    "Zilvarro, Samantha, Wynzlow, Galactum, RamBunctant, Vampie, Slywinkle, Some Dude Named Kai, Octosaur, Goran": "齐尔瓦罗、萨曼莎、温兹洛、半乳糖、RamBunctant、吸血鬼、斯lywinkle、某个名叫凯的家伙、八龙、戈兰",
    "\"Hey, we've got the first row down!\"": "“嘿，我们已经排到第一排了！”",
    "Deep Moat ": "深护城河",
    "Doubles the power of blacksmiths and hammer": "铁匠和锤子的力量加倍",
    "Doubles the power of the hammer. Hammer gains +10% per blacksmith": "使锤子的力量加倍。 每个铁匠的锤子增益 +10%",
    "Every stone of the outer wall boosts the rate": "外墙的每一块石头都会提升速度",
    "FOLK MAGIC": "民间魔术",
    "Fortified Bridge ": "坚固的桥梁",
    "FORTRESS": "堡垒",
    "FUNDAMENTALS": "基础知识",
    "Gold Pebbles ": "金鹅卵石",
    "Guards:": "守卫：",
    "MASONRY": "石工",
    "Reinforced Wine Cellar ": "加固酒窖",
    "Smithing it Out ": "锻造它",
    "Stone Walls ": "石墙",
    "Tin Hammer ": "锡锤",
    "\"Great job, but I think we'll need a bit more\"": "“干得好，但我认为我们还需要更多”",
    "\"I hope they aim for our feet\"": "“我希望他们瞄准我们的脚”",
    "A long forgotten debt has been repaid": "长期被遗忘的债务已经偿还",
    "A mature volcano breather is used to": "成熟的火山呼吸器用于",
    "A small gift": "一份小礼物",
    "A spiritual leader visits the fortress": "精神领袖参观堡垒",
    "After a mature breather is removed from the volcano, a new breather will begin growing in its place.": "当成熟的呼吸者从火山中移出后，新的呼吸者将开始在其位置生长。",
    "An abbot from the Moon Temple": "月宫方丈",
    "Arrow Supplies ": "箭头用品",
    "Arrowslits ": "箭缝",
    "Blazesapling becomes a volcano breather in 8 hours": "火焰树苗 在 8 小时内变成火山呼吸者",
    "Bronze Locks ": "青铜锁",
    "Deeper Pockets ": "更深的口袋",
    "Doubles the amount Snail Network is able to retrieve": "使 蜗牛网络 能够检索的数量加倍",
    "Doubles the power of warlocks": "使术士的力量加倍",
    "Doubles the power of weaklings. Dwarves gain +1% per weakling": "弱者的力量加倍。 每个弱者矮人获得+1%",
    "Doubles the power of witches": "使女巫的力量翻倍",
    "Doubles the power of wizards": "使法师的力量加倍",
    "Drinking doesn't need to have consequences": "喝酒不一定要产生后果",
    "Dwarf Instructor": "矮人导师",
    "Earthly Powers ": "尘世的力量",
    "Earthworks ": "土方工程",
    "Fierce Hounds ": "凶猛的猎犬",
    "Firesprout becomes heatseedling in 5 hours 30 minutes": "火芽在5小时30分钟内变成热苗",
    "Flameseed": "火焰种子",
    "Flameseed becomes firesprout in 2 hours 30 minutes": "火焰种子在 2 小时 30 分钟内变成火芽",
    "fortify": "强化",
    "Gift from the King": "国王的礼物",
    "Guards of the Outer Wall ": "外墙守卫",
    "Hammer is at": "锤子在",
    "Hangover Potion": "解酒药水",
    "Heatseedling": "热苗",
    "Heatseedling becomes blazesapling in 8 hours": "火焰树苗在8小时内变成火焰树苗",
    "Hiring bonus!": "雇佣奖励！",
    "Hypnotic Talents ": "催眠天赋",
    "It's the spiritual way to drink": "这是精神上的饮酒方式",
    "One of your generals conquered a neighboring region": "你的一位将军征服了邻近地区",
    "Package from a wealthy relative": "来自富有亲戚的包裹",
    "Payment for providing security services to a local merchant": "向当地商家提供安全服务的付款",
    "Royal Messengers:": "皇家使者：",
    "School of Magic ": "魔法学院",
    "Small donation from a local monastery": "当地修道院的小额捐赠",
    "Small Fists ": "小拳头",
    "Snail Network": "蜗居网络",
    "SNAIL NETWORK": "蜗蜗网络",
    "Spoils of war!": "战利品！",
    "Superstition ": "迷信",
    "The Darkness Within ": "内心的黑暗",
    "The flameseed was magma-infused! There's a 50% chance it will yield 2 breathers": "火焰种子充满了岩浆！ 有 50% 的机会会产生 2 次喘息机会",
    "The Weakling Alliance ": "弱者联盟",
    "They complain, but still boost rate by 2%": "他们抱怨，但仍将利率提高 2%",
    "This volcano breather will mature in": "这个火山呼吸者将在",
    "towers.": "塔。",
    "VOLCANO": "火山",
    "You are generously thanked for your service": "衷心感谢您的服务",
    "You have missed many messages, but we were able to retrieve some of it!": "您错过了很多消息，但我们能够找回其中一些！",
    "You meet a monk": "你遇见一个和尚",
    "You received a gift from a neighboring country": "您收到了来自邻国的礼物",
    "Your other uncle was assassinated": "你的另一个叔叔被暗杀了",
    "\"Hey Frilmir! We now have two full rows!\"": "“嘿弗里尔米尔！我们现在有两排了！”",
    "\"I am glad we are on our way to cover our feet from arrows and boulders\"": "“我很高兴我们正在路上，以保护我们的脚免受箭和巨石的伤害”",
    "\"I remember last week I saw some stones on the road. Was more than this\"": "“我记得上周我在路上看到了一些石头。不仅仅是这个”",
    "\"Thank you for this. Now bring the rest of the wall, please\"": "“谢谢你。现在请把墙的其余部分带来”",
    "1 volcano breather": "1 火山呼吸器",
    "Barrels of Wine ": "酒桶",
    "Bombs Away! ": "炸弹远离！",
    "Champion's Jar V": "冠军罐子V",
    "Chief's Tankard V": "酋长酒杯 V",
    "Chieftan's Jar V": "酋长的罐子 V",
    "Divine Jar V": "神坛V",
    "Doubles the power of catapults": "弹射器的威力加倍",
    "Doubles the power of weaklings. Warlocks gain +1% per weakling": "弱者的力量加倍。 每个弱者术士获得 +1%",
    "Doubles the power of weaklings. Witches gain +1% per weakling": "弱者的力量加倍。 每个弱者女巫获得+1%",
    "Doubles the power of weaklings. Wizards gain +1% per weakling": "弱者的力量加倍。 每个弱者巫师获得+1%",
    "Doubles the power of wyverns": "双足飞龙的力量加倍",
    "Each fortification provides a permanent boost to the unit's power": "每个防御工事都能永久增强部队的力量",
    "Each subsequent fortification decreases raid time by 3%": "随后的每个防御工事都会使袭击时间减少 3%",
    "Every stone of the outer wall boosts the rate even more": "外墙的每一块石头都会进一步提高速度",
    "Exorcism ": "驱魔",
    "Fireballs Galore ": "火球盛宴",
    "FORTIFICATION": "筑城",
    "Fortification costs": "防御工事费用",
    "Fortified Catapults": "强化弹射器",
    "Fortified Cheiroballistras": "强化的Cheiroballistras",
    "Fortified Crossbows": "强化弩",
    "Fortified Dwarves": "强化矮人",
    "Fortified dwarves unlock Gandlor's Cave": "强化矮人解锁甘德洛洞穴",
    "Fortified Humans": "强化人类",
    "Fortified Ogres": "强化食人魔",
    "Fortified ogres unlock cannibals": "强化食人魔解锁食人者",
    "Fortified Warlocks": "强化术士",
    "Fortified Weaklings": "强化弱者",
    "Fortified weaklings unlocks raiders": "强化弱者解锁袭击者",
    "Fortified Witches": "强化女巫",
    "Fortified Wizards": "强化巫师",
    "Fortified Wyverns": "强化飞龙",
    "Heavy Duty ": "重负",
    "Infernal Blaze ": "地狱烈焰",
    "Invisible Force ": "无形的力量",
    "Jar Class V": "V 级罐子",
    "Liquid Swords ": "液体剑",
    "Magic Duet ": "魔术二重唱",
    "Make it So! ": "就这样吧！",
    "Massive Jar V": "巨型罐子 V",
    "Monsters in the Moat ": "护城河里的怪物",
    "Potion Symbiosis ": "药水共生",
    "Second fortification increases the max amount of items you can win": "第二个防御工事增加了你可以赢得的最大物品数量",
    "Second fortification unlocks Aviary": "第二个防御工事解锁鸟舍",
    "Second fortification unlocks Hall of Giants": "第二座防御工事解锁巨人大厅",
    "Second fortification unlocks Necropolis": "第二个防御工事解锁大墓地",
    "Second fortification unlocks Tower of Dragons": "第二个防御工事解锁龙之塔",
    "Second fortification unlocks Treasury": "第二座防御工事解锁宝库",
    "Sophisticated Incantations ": "复杂的咒语",
    "Stones of Gold ": "金石",
    "Synergism ": "协同作用",
    "Tankard of Gods V": "诸神大酒杯 V",
    "Tankard V": "坦卡德五号",
    "The Greatest Forge ": "最伟大的熔炉",
    "Ultra Tankard V": "超级啤酒杯 V",
    "Underground Tunnels ": "地下隧道",
    "Warrior's Jar V": "战士的罐子V",
    "Weaklings gain +1% per wizard": "每个法师弱者获得 +1%",
    "Wheat Supplies ": "小麦供应",
    "WHITE MAGIC": "白魔法",
    "\"Almost a skyscraper, man\"": "“几乎是一座摩天大楼，伙计”",
    "Drinks and Gambling ": "饮酒与赌博 ",
    "Messengers arrive twice as frequently and stay in town twice as long": "信使到达的频率是原来的两倍，在城里停留的时间是原来的两倍",
    "ROYAL POST": "皇家邮局",
    "Sharper Sight ": "视野更锐利",
    "\"I am pretty sure this is enough to cover my ankles from enemy fire\"": "“我很确定这足以保护我的脚踝免受敌人火力的伤害”",
    "Balistraria ": "巴里斯特里亚",
    "Birds of prey ": "猛禽",
    "Blood Magic Aura ": "血魔法光环",
    "Deadly Invention ": "致命的发明",
    "Divine Jar IX": "神坛九号",
    "Divine Jar VI": "神坛VI",
    "Divine Jar VII": "神坛七号",
    "Divine Jar VIII": "神坛八号",
    "Divine Jar X": "神坛X",
    "Doubles the power of cheiroballistras": "使 cheiroballistras 的力量加倍",
    "Doubles the power of crossbows": "弩的威力加倍",
    "Flagon Class I": "酒壶 I 级",
    "Owl": "猫头鹰",
    "Treasury is located under the Hall of Giants and provides a boost to the rate based on two parameters: the amount of items encountered and how many times each item was seen. Special items that can't be acquired directly can only be either 1 or 0. For instance, if you've encountered Full Moon, it will become 1 and stay 1 even if you see it again. But for all other items the counter will increment each time it gets added to the Alchemist.": "宝库位于巨人大厅下方，根据两个参数提供速率提升：遇到的物品数量以及每个物品被看到的次数。 无法直接获得的特殊物品只能是1或0。例如，如果你遇到了满月，它就会变成1，即使你再次看到它也仍然是1。 但对于所有其他物品，每次添加到炼金术士时，计数器都会增加。",
    "In order to increment the multiplier, you must reach the target in each of the Doomed Artifacts. Use the \">>>\" button to switch between artifacts and fill each one up. When done, click \"Next target\" which will increment the Haunted Multiplier and set the next target.": "为了增加乘数，您必须达到每个注定神器的目标。 使用“>>>>”按钮在工件之间切换并填充每个工件。 完成后，单击“下一个目标”，这将增加闹鬼乘数并设置下一个目标。",
    "Souls are a transmigration currency for the Necropolis, just like Mana is for the Fortress. When you transmigrate, captured souls are going to be converted into Necropolis Levels. Each Necropolis Level provides a permanent +1% upgrade to the rate of Necropolis": "灵魂是大墓地的轮回货币，就像法力是要塞的货币一样。 当你穿越时，捕获的灵魂将被转化为大墓地等级。 每个大墓地等级都提供永久 +1% 的大墓地等级升级",
    ". It costs twice as much as the normal spin, but will yield double the time winnings.": "。 它的成本是正常旋转的两倍，但会产生双倍的时间奖金。",
    "\"Outer wall guards myth #4: Yeah, we're always grumpy... Wait, does it mean this one is": "\“外墙守卫神话＃4：是的，我们总是脾气暴躁......等等，这是否意味着这个是",
    "a myth?\"": "一个神话？”",
    "Ancient Pyramid": "古代金字塔",
    "Any spin can also win you the Seer which ensures that the deuce will be randomly generated from the pool of cards already in the wrap. You can use the Seer only before you've eliminated any cards.": "任何旋转都可以为您赢得预言家，这确保平分是从已经在包装中的牌池中随机生成的。 您只能在消除任何卡牌之前使用先知。",
    "are a special unit that are stronger than Cheiroballistras, but can only be recruited through items": "是比Cheiroballistras更强的特殊单位，但只能通过物品招募",
    "are sent to nearby locations to bring back useful items": "被送往附近地点带回有用的物品",
    "Aviary allows you to capture items that are birds. It is essentialy a set of permanent item slots.": "Aviary 允许您捕获鸟类物品。 它本质上是一组永久物品槽。",
    "Boosts archsentinels": "增强大哨兵",
    "Boosts ardemators": "增强Ardemators",
    "Boosts areds": "增强阿雷兹",
    "Boosts ghasts": "增强恶魂",
    "Boosts ghouls": "增强食尸鬼",
    "Boosts grimlords": "增强冷酷领主",
    "Cannibals are an additional unit that is unlocked through fortifying the ogres. Cannibals cannot be purchased directly, but can only be recruited through items.": "食人者是一个额外的单位，可以通过强化食人魔来解锁。 食人者不能直接购买，只能通过物品招募。",
    "Coins are based on the amount of Alchemist upgrades clicked. You can get coins through other means too.": "硬币取决于点击的炼金术士升级数量。 您也可以通过其他方式获得金币。",
    "Crescent Moon": "新月",
    "Dagger": "匕首",
    "Dwarvian Relatives": "矮人亲戚",
    "equippable item": "可装备物品",
    "Finish catching": "完成捕捉",
    "Flying Ship": "飞行船",
    "Fortifications provide permanent multipliers to the units. But most importantly many of them unlock new capabilities.": "防御工事为单位提供永久的倍增器。 但最重要的是，其中许多都解锁了新功能。",
    "Frog Rain": "青蛙雨",
    "Giant Multiplier is comprised of creatures in the towers of Mortals and Mages: every 100 creatures add 1 giant.": "巨人倍增器由凡人和法师塔中的生物组成：每 100 个生物增加 1 个巨人。",
    "Haste": "急速",
    "instant item": "即时物品",
    "introduces dragon units that boost the dwarves": "引入了可以增强矮人力量的龙单位",
    "introduces giants and the powergul Giant Multiplier": "介绍巨人和 强大巨人乘数",
    "introduces permanent item slots for bird items to permanently boost the rate": "引入鸟类物品的永久物品槽以永久提高比率",
    "is a gambling establishment where one can win items and production time": "是一个赌博场所，可以赢得物品和生产时间",
    "is an undead part of the Fortress with its own units and upgrades": "是堡垒的不死部分，有自己的单位和升级",
    "Lava Fertilizer": "熔岩肥料",
    "Necropolis is your stronghold in the land of the dead with its separate rate and currency. But it is connected to the main fortress: it provides a Haunted Multiplier which multiplies fortress rate.": "墓地是您在死亡之地的据点，具有独立的汇率和货币。 但它与主要塞相连：它提供了一个闹鬼倍增器，可以使要塞率倍增。",
    "Necropolis Level:": "墓地等级：",
    "not": "不是",
    "provides a boost to the rate based on the amount of seen items": "根据看到的项目数量提高费率",
    "Send Raiders": "送攻略",
    "Shadow Attractor": "阴影吸引器",
    "Souls captured:": "捕获的灵魂：",
    "special item": "特别项目",
    "Strange Bottle": "奇怪的瓶子",
    "The Aviary will reset after each transmigration, however if you manage to capture every specie, the Aviary will stay full permanently.": "每次迁移后鸟舍都会重置，但是如果您设法捕获所有物种，鸟舍将永久保持满状态。",
    "the grand spin": "大旋转",
    "The power of cannibals depends not only on the amount of the unit itself, but also on the amount of units in the towers of Mortals and Mages.": "食人者的力量不仅取决于单位本身的数量，还取决于凡人塔和法师塔中的单位数量。",
    "The two closed cards are the deuce. The five open cards are the wrap. Your goal is to match all the cards of the wrap against the deuce. You can click any two cards in the wrap to remove them, at which point the deuce will be rolled.": "两张封闭的牌是平局。 五张打开的卡片是换行。 您的目标是将所有牌都与平局相匹配。 您可以单击包裹中的任意两张牌将其移除，此时将掷出平分。",
    "Thunder": "雷",
    "Transmigrations will reset all counters back to 1, but if an item was encountered it will always stay at least as 1.": "迁移会将所有计数器重置回 1，但如果遇到某个物品，它将始终至少保持为 1。",
    "Treasure Chest": "百宝箱",
    "Treasury Factor:": "财务因素：",
    "When all items have been encountered, transmigrations will stop resetting item counters, allowing for unlimited growth across runs": "当遇到所有物品时，迁移将停止重置物品计数器，从而允许运行中无限增长",
    "Wing Factor:": "机翼系数：",
    "You also win items. Normal spin will offer you some standard items and Cannibals (provided they are unlocked). Grand spin offers a wide variety of advanced items.": "您还可以赢得物品。 正常旋转将为您提供一些标准物品和食人者（前提是它们已解锁）。 大旋转 提供各种高级物品。",
    "You can also spin after removing just a single card. This is called": "您也可以在取出一张卡片后旋转。 这就是所谓的",
    "You cannot have several birds of the same species, each bird must be unique.": "您不能拥有同一物种的多只鸟，每只鸟都必须是独一无二的。",
    "You may also choose to not recast if you know that the amount of units has fallen below what you previously had.": "如果您知道单位数量已低于之前的数量，您也可以选择不重铸。",
    "You need to click the \"Recast Giants\" button if you would like to recalculate the Giant Multiplier when more creatures are hired.": "如果您想在雇用更多生物时重新计算巨人乘数，您需要单击“重铸巨人”按钮。",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Garden": "花园",
    "Smaug": "Smaug",
    "Alchemist": "炼金术士",
    "Giant Multiplier": "巨人乘数",
    "Fire Multiplier": "火力乘数",
    "Offline mining": "离线挖矿",
    "Known issues": "已知的问题",
    "Wicked Quests": "邪恶的任务",
    "End of content": "内容结束",
    "Diamonds": "钻石",
    "Future plans": "未来的计划",
    "Compatibility": "兼容性",
    "Reincarnation": "投胎",
    "Wine Cellar": "酒窖",
    "Graveyard": "墓地",
    "Medallions": "奖章",
    "Messengers": "信使",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "lock": "lock",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'I',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑: ",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式: ",
    "In-line Exponent: ": "直列指数: ",
    "Single-Tab Mode: ": "单标签模式: ",
    "Time Played: ": "已玩时长: ",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示: ",
    "Succubi: ": "魅魔: ",
    "Skeletons: ": "骷髅: ",
    "Spirits: ": "精灵: ",
    "Price: ": "价格: ",
    "Ore Mines: ": "矿山: ",
    "Drunken Multiplier: ": "醉酒乘数: ",
    "Size: ": "尺寸: ",
    "Cheiroballistras: ": "弩炮: ",
    "Catapults: ": "弹射器: ",
    "Crossbows: ": "弩: ",
    "Weaklings: ": "弱者: ",
    "Ore: ": "矿石: ",
    "Dwarves: ": "矮人: ",
    "Humans: ": "人类: ",
    "Collect: ": "收集: ",
    "Power: ": "力量: ",
    "Loot: ": "战利品: ",
    "Enemy HP: ": "敌人生命值: ",
    "Ogres: ": "食人魔: ",
    "Specters: ": "幽灵: ",
    "Diamonds: ": "钻石: ",
    "Level: ": "等级: ",
    "Target: ": "目标: ",
    "Next target: ": "下一个目标: ",
    "Warlocks: ": "术士: ",
    "Wizards: ": "巫师: ",
    "Wyverns: ": "飞龙: ",
    "Witches: ": "女巫: ",
    "Time: ": "时间: ",
    "Giant Dwarves: ": "巨型矮人: ",
    "Giant Witches: ": "巨型女巫: ",
    "Giant Weaklings: ": "巨型弱者: ",
    "Giant Ogres: ": "巨型食人魔: ",
    "Giant Warlocks: ": "巨型术士: ",
    "Giant Wyverns: ": "巨型飞龙: ",
    "Giant Wizards: ": "巨型巫师: ",
    "Giant Humans: ": "巨型人类: ",
    "Wicked Multiplier: ": "邪恶乘数: ",
    "Doomed Artifact ": "注定的神器 ",
    "Blacksmiths: ": "铁匠：",
    "Areds: ": "阿雷兹: ",
    "Bet: ": "赌注: ",
    "Andlyns: ": "安德林斯: ",
    "Coins: ": "金币: ",
    "Archsentinels: ": "大哨兵: ",
    "Grandliches: ": "大巫妖: ",
    "Grimlords: ": "恐怖领主: ",
    "Ghasts: ": "鬼魂: ",
    "Ghouls: ": "食尸鬼: ",
    "Ardemators: ": "阿德玛特: ",
    "Credits": "鸣谢",
    "Boosts rate by ": "提升效率 ",
    "Class: ": "等级: ",
    "Increasing the rate by: ": "提升效率: ",
    "Contribution: ": "贡献：",
    "Dreadshield: ": "恐惧之盾：",
    "Cannibals: ": "食人者：",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^制作(.+)$/,
    /^增加(.+)$/,
    /^雇佣(.+)$/,
    /^购买(.+)$/,
    /^([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)k\/s$/,
    /^([\d\.]+)M\/s$/,
    /^x([\d\.]+)M$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)k$/,
    /^([\d\.]+)c$/,
    /^([\d\.]+)kS$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+)T$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^\-([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = []

//正则替换，带数字的固定格式句子
//纯数字: (\d+)
//逗号: ([\d\.,]+)
//小数点: ([\d\.]+)
//原样输出的字段: (.+)
//换行加空格: \n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^at (.+) Mana$/, '在 $1 法力'],
    [/^Ale Mug Class (.+)$/, '啤酒杯等级 $1'],
    [/^Junior Tankard Class (.+)$/, '少年大啤酒杯等级 $1'],
    [/^Goblet Class (.+)$/, '高脚杯等级 $1'],
    [/^Tankard Class (.+)$/, '大啤酒杯等级 $1'],
    [/^Tea Cup Class (.+)$/, '茶杯等级 $1'],
    [/^([\d\.]+)\/sec$/, '$1\/秒'],
    [/^([\d\.]+)\/s$/, '$1\/秒'],
    [/^\+([\d\.]+)\/s$/, '+$1\/秒'],
    [/^([\d\.,]+)\/sec$/, '$1\/秒'],
    [/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+) hours ([\d\.]+) minute$/, '$1 小时 $2 分钟'],
    [/^([\d\.]+) hours ([\d\.]+) minutes$/, '$1 小时 $2 分钟'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^Raise ([\d\.,]+)$/, '增加 $1'],
    [/^Make ([\d\.,]+)$/, '制作 $1'],
    [/^Hire ([\d\.,]+)$/, '雇佣 $1'],
    [/^Buy ([\d\.,]+)$/, '购买 $1'],
    [/^Exhibit ([\d\.,]+)$/, '展览品 $1'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^([\d\.,]+)(.+)warlocks$/, '$1 术士'],
    [/^([\d\.,]+)(.+)witches$/, '$1 女巫'],
    [/^([\d\.,]+)(.+)wyverns$/, '$1 飞龙'],
    [/^([\d\.,]+)(.+)catapults$/, '$1 弹射器'],
    [/^([\d\.,]+)(.+)ballistras$/, '$1 弩炮'],
    [/^([\d\.,]+) Humans$/, '$1 人类'],
    [/^([\d\.,]+)(.+)humans$/, '$1 人类'],
    [/^([\d\.,]+) Weaklings$/, '$1 弱者'],
    [/^([\d\.,]+)(.+)weaklings$/, '$1 弱者'],
    [/^([\d\.,]+) Crossbows$/, '$1 弩'],
    [/^([\d\.,]+)(.+)crossbows$/, '$1 弩'],
    [/^([\d\.,]+) Wizards$/, '$1 巫师'],
    [/^([\d\.,]+)(.+)wizards$/, '$1 巫师'],
    [/^([\d\.,]+) Witches$/, '$1 女巫'],
    [/^([\d\.,]+) Wyverns$/, '$1 飞龙'],
    [/^([\d\.,]+) Grandliches$/, '$1 大巫妖'],
    [/^([\d\.,]+)(.+)humans$/, '$1 人类'],
    [/^([\d\.,]+)(.+)smiths$/, '$1 铁匠'],
    [/^([\d\.,]+) Succubi$/, '$1 魅魔'],
    [/^([\d\.,]+) Blacksmiths$/, '$1 铁匠'],
    [/^([\d\.,]+) Warlocks$/, '$1 术士'],
    [/^([\d\.,]+) Cannibals$/, '$1 食人者'],
    [/^([\d\.,]+)(.+)cannibals$/, '$1 食人者'],
    [/^([\d\.,]+) Ogres$/, '$1 食人魔'],
    [/^([\d\.,]+)(.+)ogres$/, '$1 食人魔'],
    [/^([\d\.,]+) Dwarves$/, '$1 矮人'],
    [/^([\d\.,]+)(.+)dwarves$/, '$1 矮人'],
    [/^([\d\.,]+) Medallions$/, '$1 奖章'],
    [/^([\d\.,]+)(.+)medallions$/, '$1 奖章'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本: $1 点数'],
    [/^Req: (.+) elves$/, '要求: $1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求: $1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途: $1\/'],
    [/^workers: (\d+)\/$/, '工人: $1\/'],

]);